### ISSUE TITLE
Login widget

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/wpphpbbunicorn#6]
Half of login widget is broken for me:
Forum admin link not work (it redirects to) mysite.pl/adm/?sid=263590ea6d30c6f0ae9730a631577900
and I think it should redirect to mysite.pl/forum/adm/?sid=263590ea6d30c6f0ae9730a631577900

**Comment by Wardormeur** [comment]
Indeed, fix incoming.

**Comment by Wardormeur** [comment]
Hum.
It works on mine, so i suppose it comes from your config. I know this is gonna be wrong for the rest of it, but could you give /forum a try instead of //forum ? Just to test this widget and confirm my theory

**Comment by RARgames** [comment]
I tried /forum but it's the same

**Comment by RARgames** [comment]
When I click forum admin many times it redirects to mysite.pl/adm/adm/adm/adm/and_sid
You can still test this live on my installation of wp(I didn't delete your user

**Comment by Wardormeur** [comment]
Cool, will give it a try asap

**Comment by RARgames** [comment]
maybe you did something but now there is a problem with path in wp:
The folder ucp does not exists in the path you have enter

**Comment by RARgames** [comment]
Maybe you did something. There is a problem with path in wp:

The folder ucp does not exists in the path you have enter
I didn't change the path

**Comment by Wardormeur** [comment]
Neither did i

**Comment by RARgames** [comment]
It's strange. Without changing the path bridge disconnected and I can't connect it using old paths: //forum/ /forum/

**Comment by Wardormeur** [comment]
Not really available before this WE to look at it, actually, will keep you updated

**Comment by RARgames** [comment]
NP, I'm on vacation right now so I have a little time too

**Comment by Wardormeur** [comment]
Hey,
Can't login on your WP (invalid username) and your forum seems down, will give it a try later :)

**Comment by RARgames** [comment]
fixed, I didn't clear the cache after changing db password

**Comment by RARgames** [comment]
the path is working too(it was linked to offline forums)

only the widget not work

**Comment by Wardormeur** [comment]
Ok, this makes more sense :+1: 
Still can't login bcause of wpu (redirecting me to /forum), will create a user on the forum during the day :)

**Comment by RARgames** [comment]
you are trying to login using widget? on main site?

**Comment by Wardormeur** [comment]
Can't access the main site, i have your nice bird page denying me access :)
So i try through /wp-admin which redirect me to /forum

**Comment by RARgames** [comment]
Ahh do you have new ip?

**Comment by Wardormeur** [comment]
seems like Y, i may have a dynamic IP (just moved, didn't know), but it doesn't solve the problem of being redirected when you only have a WP account

**Comment by RARgames** [comment]
I thought redirect comes from bridge(feature)
Only wp accounts seems broken

**Comment by RARgames** [comment]
And I think it's good because of the bridge system and user administration from phpbb

**Comment by Wardormeur** [comment]
That's totally normal : you can't login from phpbb with a WPuser.
What i'm saying is that it miss a feature for WPuser only to login :)

**Comment by RARgames** [comment]
yeah I know

send me your new ip and i'll add you

**Comment by RARgames** [comment]
Do you have any new idea how to fix this?

**Comment by Wardormeur** [comment]
It may, yes :)
I'll resend you my ip tonight or tomorrow morning

**Comment by Wardormeur** [comment]
Fixed, small typo, too many "p", didn't see that ><

**Comment by RARgames** [comment]
Thx for all help
