### ISSUE TITLE
session login

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/wpphpbbunicorn#9]
I think session login is bugged:

When I log in to my site using widget on main site(test user: no admin perms)
If I log out on main site(not dashboard) or forum site and than log in using anything(widget, forum login) (admin)I got logged in correctly on forums but on main site I'm kind of logged in(widget is showing that I'm logged as admin but I can't change anything on site, when i do /wp-admin it shows that I'm logged as test user

**Comment by Wardormeur** [comment]
I'll need to review that
If possible, try to describe it with different scenario as of 
'Blog login->logout forum->should be logged-out on blog but is not' 
It's easier to understand what behaviour you're expecting and how to reproduce it :)

**Comment by RARgames** [comment]
ok I'll try

user test
blog login>logout widget or forum
user admin
login widget or forum>not logged in to the main site(wp) as admin(logged as test)

**Comment by Wardormeur** [comment]
So it seems it actually doesn't disconnect the WP user. Will look after it this sunday in best case

**Comment by Wardormeur** [comment]
Should be fixed.
However, it means that you can't login without phpbb anymore :)
I'll probably later add a switch to allow WP user with WP-PHPBB users

**Comment by RARgames** [comment]
ok, thanks;
I'll check it tomorrow

**Comment by RARgames** [comment]
error when trying to activate plugin:

Warning: require(D:\Dev\UniServerZ\www\qwp\wp-content\plugins\wp-phpbb-unicorn\inc/cache/functions_content.php): failed to open stream: No such file or directory in /wp-content/plugins/wpphpbbunicorn-new/inc/cache/common.php on line 61

Fatal error: require(): Failed opening required 'D:\Dev\UniServerZ\www\qwp\wp-content\plugins\wp-phpbb-unicorn\inc/cache/functions_content.php' (include_path='/wp-content/plugins/wpphpbbunicorn-new/vendor/phpunit/php-text-template:/wp-content/plugins/wpphpbbunicorn-new/vendor/phpunit/php-timer:.:/usr/local/php/pear5') in /wp-content/plugins/wpphpbbunicorn-new/inc/cache/common.php on line 61

**Comment by Wardormeur** [comment]
Reupdate, those files comes from my own cached version.Either save your parameters to regenerate them or just empty the wp/wp-content/plugins/wpphpbbu/inc/cache folder
I just exluded those files in the latest commit to avoid this not-so-new error :(

**Comment by RARgames** [comment]
it seems ok now

but one small thing after logout(widget) I'm redirected to forum page and sometimes get error with:hazardous link:

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 2352
CALL: trigger_error()

FILE: [ROOT]/includes/functions.php
LINE: 2917
CALL: redirect()

FILE: [ROOT]/ucp.php
LINE: 84
CALL: login_box()

**Comment by RARgames** [comment]
I saw this error a few times, now it's normal.
I think it's not good to redirect out of main page after logout

**Comment by Wardormeur** [comment]
By that you mean that you expect it to redirect to the blog main page after disconnection? or the forum main page?

**Comment by RARgames** [comment]
blog main page should be better

**Comment by RARgames** [comment]
where is this redirect in the code?(can't find it)
I'll change this only for me(it's really annoying for me)

**Comment by RARgames** [comment]
idk what I have to do after updating your plugin(I have this cache error again)
How to regenerate cache? 

nt/plugins/wpphpbbunicorn/inc/cache/functions_content.php): No such file or directory in /wp-content/plugins/wpphpbbunicorn/inc/Proxy.php on line 8

Warning: unlink(/wp-content/plugins/wpphpbbunicorn/inc/cache/common.php): No such file or directory in /wp-content/plugins/wpphpbbunicorn/inc/Proxy.php on line 9

Warning: unlink(/wp-content/plugins/wpphpbbunicorn/inc/cache/functions_user.php): No such file or directory in /wp-content/plugins/wpphpbbunicorn/inc/Proxy.php on line 10

Warning: file_put_contents(/wp-content/plugins/wpphpbbunicorn/inc/cache/functions_content.php): failed to open stream: No such file or directory in /wp-content/plugins/wpphpbbunicorn/inc/Proxy.php on line 44

Warning: file_put_contents(/wp-content/plugins/wpphpbbunicorn/inc/cache/functions_user.php): failed to open stream: No such file or directory in /wp-content/plugins/wpphpbbunicorn/inc/Proxy.php on line 63

Warning: file_put_contents(/wp-content/plugins/wpphpbbunicorn/inc/cache/common.php): failed to open stream: No such file or directory in /wp-content/plugins/wpphpbbunicorn/inc/Proxy.php on line 94

Edit: I think plugin does not have perm on the server to create cache files(when I created empty cache folder, it regenerated, but visual editor is broken again) How can I fix it?(in cache?!?)

**Comment by Wardormeur** [comment]
cache regeneration is done by saving the parameters of the plugin
Rediretction issue is a bit more complicated than just "redirection", as it actually lose the wp_nonce for admin-bar disconnection (but works for the widget); so this is kindof strange scenario I need to figure out

**Comment by RARgames** [comment]
yeah the plugin regenerated cache.
before regeneration visual editor was working
after it isn't working

**Comment by Wardormeur** [comment]
Well, it's not like I changed much... Last time is was a unused variable name which was causing a error in the creation of the forum list. Do you have any forum to display? Are you logged-in as a forum-user ?

**Comment by RARgames** [comment]
Forum-yes
I logged in using wpphpbb widget

EDIT: you can still log in on my site and check

**Comment by RARgames** [comment]
When I'm not login into forum admin panel(can't switch to visual editor, I have this error:

] PHP Warning: in file /wp-includes/option.php on line 787: Cannot modify header information - headers already sent by (output started at /wp-includes/functions.php:1389)
[phpBB Debug] PHP Warning: in file /wp-includes/option.php on line 788: Cannot modify header information - headers already sent by (output started at /wp-includes/functions.php:1389)

but when I'm only log in by widget and than to panel I don't see the error(visual editor is open but not readable)

**Comment by Wardormeur** [comment]
It may be a small issue, I'll update the version today, have a look at it after ;)

**Comment by Wardormeur** [comment]
Should be fixed

**Comment by RARgames** [comment]
visual editor still not working
and on forum publication:

Fatal error: Call to a member function fetch_assoc() on a non-object in /wp-content/plugins/wpphpbbunicorn/inc/Forum.php on line 12

EDIT: redirect works fine. It is your plugins screen "are you sure to log out"

**Comment by Wardormeur** [comment]
The screen is not mine, but WP's. It sems you have a bigger issue, I'll have a look at your instance directly, because I didn't change the publication process, so..

**Comment by Wardormeur** [comment]
Well, if you deactivate it, I won't be able to help you out on this one..

**Comment by RARgames** [comment]
So this is the only way of repairing redirection issue?(making redirection through the logout screen)
This issue only appears in my instance?
What about VE and Forum Publication?

EDIT: this screen only appears when I log out using widget

**Comment by Wardormeur** [comment]
This is not the only way, but this is the fastest way to do it until I find the proper way : this is mostly a bug inside the feature ;)
For VE & Forum Publi, I need to investigate more on your website, cause I don't have this issue on mine (again)..

**Comment by RARgames** [comment]
ok, so please take a look and say what was causing the issue :D

**Comment by RARgames** [comment]
Now VE and FP are working again. :P thanks

I analyzed the logout screen issue:
Widget log in>widget log out>are you sure to logout screen
widget log in>go to any page>widget log out>NO are you sure screen

EDIT: quick solution:(idk it is possible) after going first time in session to any page(not /forum pages)=reload page

**Comment by Wardormeur** [comment]
nope, better find a proper solution

**Comment by RARgames** [comment]
I didn't notice it. Maybe it would help(not sure you saw the url)
this is the url of the "are u sure" page:(open in browser)

http://www.mysite.pl/wp-login.php?action=logout&redirect_to=http%3A%2F%2Fwww.mysite.pl&_wpnonce=dd834bc446%3Cb%3E[phpBB%20Debug]%20PHP%20Warning%3C/b%3E:%20in%20file%20%3Cb%3E/wp-includes/pluggable.php%3C/b%3E%20on%20line%20%3Cb%3E1207%3C/b%3E:%20%3Cb%3ECannot%20modify%20header%20information%20-%20headers%20already%20sent%20by%20%28output%20started%20at%20/wp-content/themes/customizr/header.php:13%29%3C/b%3E%3Cbr%20/%3E

the phpbb debug warning

Line 1207 in pluggable:     header("Location: $location", true, $status);

If I can help you somehow just write

**Comment by Wardormeur** [comment]
this is your theme which seems faulty
content/themes/customizr/header.php lien 13
And no, it won't change much anyway :)

**Comment by RARgames** [comment]
I tried using twenty eleven theme= the same "are u sure" page

13 line in header.php of my theme(customizr)
<  html class="ie ie7" <?php language_attributes(); ?  >  >
without the extra spaces

at twenty anything theme it's the same line

**Comment by Wardormeur** [comment]
That's what i said : the warning comes from your theme, but the fact that the page is dislpayed is unrelated ;)

**Comment by RARgames** [comment]
this page appears with every plugin when bridge is turned on
when I disabled bridge and use other plugin(logout widget) everything is working fine
I tested with login-logout plugin

**Comment by Wardormeur** [comment]
What do you mean with every plugin? What other cases display this "are you sure" page?

**Comment by RARgames** [comment]
wpphpbb unicorn=on

I tried using login-logout plugin(widget) or login widget with shortcode or nice login widget
when i log out I had "are u sure"

wpphpbb unicorn=off
I tried only with login-logout(widget)
when I log out I was redirected to home page(without are u sure page)

**Comment by Wardormeur** [comment]
Yep, i told you I know it happens, but until i find another way, that's the only way to ensure it works properly
I don't give up on finding a solution but this isn't the only thing i do of my life :)

**Comment by RARgames** [comment]
I know, just trying to help

**Comment by Wardormeur** [comment]
Should be fixed as of todays pushs

**Comment by RARgames** [comment]
Everything is working fine :P 
Thanks
